import type { Request, Router } from 'express';
import { prisma } from '../lib/prisma.js';
import { sendAdminEmail } from '../lib/email.js';
import { logAdminAction } from './audit.js';
import type { AdminSessionUser } from './auth.js';

declare module 'express-session' { interface SessionData { adminUser?: AdminSessionUser } }
function esc(v: string) { return v.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)); }
function field(req: Request, name: string) { const v=(req as unknown as {fields?:Record<string,string|string[]|undefined>}).fields?.[name]; return typeof v==='string'?v.trim():''; }
function page(users:Array<{id:string;fullName:string;email:string}>,partners:Array<{id:string;businessName:string;email:string}>,flash='') {
 const userOptions=users.map(x=>`<option value="${esc(x.id)}">${esc(x.fullName)} — ${esc(x.email)}</option>`).join('');
 const partnerOptions=partners.map(x=>`<option value="${esc(x.id)}">${esc(x.businessName)} — ${esc(x.email)}</option>`).join('');
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Send email</title><style>body{font:15px Arial,sans-serif;background:#f4f6fa;color:#18212f;max-width:850px;margin:30px auto;padding:0 18px}a{color:#0756b8;text-decoration:none}.card{background:#fff;border-radius:14px;padding:24px;box-shadow:0 2px 12px #0001;margin-top:20px}label{display:block;font-weight:bold;margin:16px 0 6px}input,select,textarea{box-sizing:border-box;width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}textarea{min-height:180px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:16px}button{margin-top:18px;border:0;border-radius:8px;padding:12px 18px;background:#0b2f73;color:#fff;font-weight:bold;cursor:pointer}.flash{padding:12px;background:#e6f4ea;border-radius:8px;color:#155724}.hint{color:#64748b;font-size:13px}@media(max-width:600px){.row{grid-template-columns:1fr}}</style></head><body><p><a href="/admin">← Admin dashboard</a></p><h1>Send an email</h1><p class="hint">Email one customer or partner, or send an announcement to the full selected audience. Messages are sent using Resend and recorded in the admin audit log.</p>${flash?`<p class="flash">${esc(flash)}</p>`:''}<form class="card" method="post" action="/admin/email-composer"><div class="row"><div><label>Audience</label><select id="audience" name="audience"><option value="CUSTOMERS">Customers</option><option value="PARTNERS">Partners</option></select></div><div><label>Recipients</label><select name="recipient_mode" id="mode"><option value="ALL">Everyone in this audience</option><option value="ONE">One person</option></select></div></div><label>Choose a recipient when sending to one person</label><select id="recipient" name="recipient_id"><option value="">Select a customer</option><optgroup label="Customers">${userOptions}</optgroup><optgroup label="Partners">${partnerOptions}</optgroup></select><label>Subject</label><input name="subject" required minlength="3" maxlength="200"><label>Message</label><textarea name="message" required minlength="2" maxlength="10000" placeholder="Write your message..."></textarea><button>Send email</button></form><script>const a=document.querySelector('#audience'),m=document.querySelector('#mode'),r=document.querySelector('#recipient');function sync(){r.required=m.value==='ONE';for(const g of r.querySelectorAll('optgroup'))g.hidden=(a.value==='CUSTOMERS')!==(g.label==='Customers')}a.addEventListener('change',sync);m.addEventListener('change',sync);sync()</script></body></html>`;
}
export function registerEmailComposerRoutes(router:Router) {
 router.get('/email-composer',async(req,res)=>{const admin=req.session?.adminUser;if(!admin)return res.redirect('/admin/login');if(admin.role==='SUPPORT')return res.status(403).type('html').send('<p>Finance or Super Admin access required.</p>');const [users,partners]=await Promise.all([prisma.user.findMany({where:{accountStatus:'ACTIVE'},select:{id:true,fullName:true,email:true},orderBy:{fullName:'asc'},take:2000}),prisma.partner.findMany({select:{id:true,businessName:true,email:true},orderBy:{businessName:'asc'},take:2000})]);res.type('html').send(page(users,partners,typeof req.query.flash==='string'?req.query.flash:''));});
 router.post('/email-composer',async(req,res)=>{const admin=req.session?.adminUser;if(!admin)return res.redirect('/admin/login');if(admin.role==='SUPPORT')return res.status(403).type('html').send('<p>Finance or Super Admin access required.</p>');try{const audience=field(req,'audience'),mode=field(req,'recipient_mode'),id=field(req,'recipient_id'),subject=field(req,'subject'),message=field(req,'message');if(!['CUSTOMERS','PARTNERS'].includes(audience)||!['ALL','ONE'].includes(mode)||subject.length<3||subject.length>200||message.length<2||message.length>10000||(mode==='ONE'&&!id))throw new Error('Check the audience, recipient, subject and message.');const rows=audience==='CUSTOMERS'?await prisma.user.findMany({where:{accountStatus:'ACTIVE',...(mode==='ONE'?{id}:{})},select:{email:true},take:mode==='ONE'?1:10000}):await prisma.partner.findMany({where:mode==='ONE'?{id}:{},select:{email:true},take:mode==='ONE'?1:10000});if(!rows.length)throw new Error('No recipients were found.');const result=await sendAdminEmail({recipients:rows.map(x=>x.email),subject,message});await logAdminAction({adminId:admin.id,action:'SEND_ADMIN_EMAIL',targetType:audience,metadata:{audience,recipientMode:mode,recipientCount:rows.length,subject,sent:result.sent}});if(!result.sent)throw new Error(result.error??'Email delivery failed.');res.redirect('/admin/email-composer?flash='+encodeURIComponent(`Email sent to ${rows.length} recipient${rows.length===1?'':'s'}.`));}catch(e){res.redirect('/admin/email-composer?flash='+encodeURIComponent(e instanceof Error?e.message:'Could not send email.'));}});
}