import { useEffect, useState, type FormEvent } from 'react';
import AppShell from '../components/AppShell';
import { api, ApiError } from '../lib/api';
import { PinConfirmDialog } from '../components/PinConfirmDialog';

export default function BvnCrmPage() {
  const [ticketId, setTicketId] = useState(''); const [price, setPrice] = useState<number>(); const [pinOpen, setPinOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { api.get<{ data: { unit_price: number } }>('/bvn-crm/price').then((r) => setPrice(r.data.unit_price)).catch(() => setMessage('Unable to load service price.')); }, []);
  function prepare(event: FormEvent) { event.preventDefault(); if (!/^\d{8}$/.test(ticketId)) return setMessage('Ticket ID must be exactly 8 digits.'); setMessage(''); setPinOpen(true); }
  async function submit(pin: string) { setPinOpen(false); setBusy(true); try { const r = await api.post<{ message: string; data: { reference: string } }>('/bvn-crm/submit', { ticket_id: ticketId, pin }); setMessage(`${r.message} Reference: ${r.data.reference}`); setTicketId(''); } catch (e) { setMessage(e instanceof ApiError ? e.message : 'Request failed. Please try again.'); } finally { setBusy(false); } }
  return <AppShell><main className="mx-auto max-w-2xl"><section className="rounded-2xl border border-parchment-line bg-parchment p-6"><p className="font-body text-sm font-semibold text-gold-700">Identity services</p><h1 className="mt-1 font-display text-3xl font-bold text-ink">BVN CRM</h1><p className="mt-2 font-body text-sm text-ink-600">Submit your 8-digit BVN CRM Ticket ID for an agent to follow up. Processing takes 24–48 hours.</p><p className="mt-4 font-body font-semibold text-ink">Service cost: {price === undefined ? 'Loading…' : `₦${price.toLocaleString('en-NG')}`}</p><form onSubmit={prepare} className="mt-5 space-y-4"><label className="block font-body text-sm text-ink-600">Ticket ID<input required inputMode="numeric" maxLength={8} value={ticketId} onChange={(e) => setTicketId(e.target.value.replace(/\D/g, '').slice(0, 8))} placeholder="e.g. 88248123" className="mt-1 w-full rounded-xl border border-parchment-line bg-cream p-3 text-ink" /></label><button disabled={busy} className="w-full rounded-xl bg-gold-500 py-3 font-display font-semibold text-ink disabled:opacity-60">{busy ? 'Submitting…' : 'Continue to PIN confirmation'}</button></form>{message && <p className="mt-4 rounded-xl bg-cream p-3 font-body text-sm text-ink-600">{message}</p>}</section></main><PinConfirmDialog open={pinOpen} onClose={() => setPinOpen(false)} onVerified={submit} /></AppShell>;
}
