import { useState, type FormEvent } from 'react';
import { Loader2, Send } from 'lucide-react';
import AppShell from '../components/AppShell';
import { api } from '../lib/api';

export default function ManualServiceRequestPage({ title, prompt }: { title: string; prompt: string }) {
  const [details, setDetails] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); if (details.trim().length < 8) { setMessage('Please enter the details needed to process this request.'); return; } setBusy(true); setMessage(''); try { await api.post('/support/tickets', { subject: `${title} Request`, message: `${title} request\n\n${details.trim()}` }); setDetails(''); setMessage('Request received. K-Tech Solutions will process it and upload any completed document to My Deliveries.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to submit this request.'); } finally { setBusy(false); } }
  return <AppShell><div className="mx-auto max-w-3xl"><header className="rounded-2xl border border-gold-500/40 bg-ink p-6 text-cream"><p className="text-sm font-semibold text-gold-300">K-Tech Solutions service</p><h1 className="mt-1 text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-cream/75">{prompt}</p></header><form onSubmit={submit} className="mt-6 rounded-2xl border border-parchment-line bg-parchment p-5"><label className="block text-sm font-semibold text-ink">Request details<textarea required value={details} onChange={(event) => setDetails(event.target.value)} rows={7} placeholder="Enter all relevant details. Do not include your password or OTP." className="mt-2 w-full resize-y rounded-xl border border-parchment-line bg-cream p-3 text-sm" /></label>{message && <p className={`mt-4 rounded-xl p-3 text-sm ${message.startsWith('Request received') ? 'bg-success-500/10 text-success-700' : 'bg-ember-500/10 text-ember-600'}`}>{message}</p>}<button disabled={busy} className="mt-4 flex items-center gap-2 rounded-xl bg-gold-500 px-5 py-3 text-sm font-bold text-ink disabled:opacity-60">{busy ? <Loader2 size={16} className="animate-spin"/> : <Send size={16}/>}Submit request</button></form></div></AppShell>;
}
