import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';

/**
 * Shared types + drawing helpers for the identity-slip PDFs we render
 * ourselves (see render-identity-slip-pdf.ts and identity-slip-layouts.ts).
 * Only used for providers that return JSON, not a finished PDF
 * (FranceVerified); Techhub slips arrive as ready-made PDFs.
 */

export type PdfDoc = InstanceType<typeof PDFDocument>;

export type IdentitySlipPhoto = { base64: string; format?: 'jpeg' | 'png' };
export type IdentitySlipField = { label: string; value: string | null | undefined };

/**
 * Which look a slip gets. NIN slips have four distinct layouts:
 *   premium  - gold framed slip with QR (original premium look)
 *   standard - "digital slip": ID-card style panel with QR
 *   regular  - plain bordered form grid, photo top-right
 *   vnin     - minimal-disclosure verification record (NIN number withheld)
 * BVN slips only use premium/standard (their original two looks).
 * Rendering tier is purely presentation - every tier is built from the same
 * provider data.
 */
export type IdentitySlipTier = 'premium' | 'standard' | 'regular' | 'vnin';
export type IdentitySlipTitle = 'NIN Slip' | 'BVN Slip';

export type IdentitySlipParams = {
  title: IdentitySlipTitle;
  subtitle: string;
  reference: string;
  fields: IdentitySlipField[];
  photo?: IdentitySlipPhoto;
  issuedAt: Date;
  /** Omitted = the original plain look. */
  tier?: IdentitySlipTier;
};

// Our own wording - deliberately NOT NIMC's: these are third-party reports,
// so they carry K-TECH branding and never reproduce a government emblem,
// agency logo, or "issued by" language.
export const SLIP_DISCLAIMER =
  'Third-party identity verification report generated by K-TECH SOLUTIONS from verified provider data. This is not a document issued or certified by NIMC.';

export function valueForPdf(value: string | null | undefined): string {
  return value === undefined || value === null || value.trim() === '' || value === '****' ? 'N/A' : value;
}

/** Accept either raw base64 or a browser-friendly data URL from a provider. */
export function imageBuffer(value: string): Buffer {
  const base64 = value
    .trim()
    .replace(/^data:image\/(?:png|jpe?g|webp);base64,/i, '')
    .replace(/\s/g, '');
  return Buffer.from(base64, 'base64');
}

export function formatIssued(date: Date): string {
  return date.toISOString().replace('T', ' ').replace(/\.\d{3}Z$/, ' UTC');
}

/** 11-digit NINs print as "1234 567 8901"; anything else is shown untouched. */
export function formatNin(value: string | undefined): string | undefined {
  if (!value) return value;
  const digits = value.replace(/\s/g, '');
  return /^\d{11}$/.test(digits) ? digits.replace(/^(\d{4})(\d{3})(\d{4})$/, '$1 $2 $3') : value;
}

/**
 * Creates the document, lets `draw` paint it, and resolves with the PDF as
 * base64. `compress: false` exists so tests can read the text back out.
 */
export function buildPdf(draw: (doc: PdfDoc) => void, options: { margin?: number; compress?: boolean } = {}): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: options.margin ?? 40, compress: options.compress ?? true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks).toString('base64')));
    doc.on('error', reject);
    try {
      draw(doc);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/** Draws the photo inside the box; returns false (and draws nothing) if it can't be embedded. */
export function drawPhoto(doc: PdfDoc, photo: IdentitySlipPhoto | undefined, x: number, y: number, w: number, h: number): boolean {
  if (!photo) return false;
  try {
    const buffer = imageBuffer(photo.base64);
    doc.rect(x, y, w, h).fill('#f3f4f6');
    doc.image(buffer, x, y, { fit: [w, h], align: 'center', valign: 'center' });
    return true;
  } catch (error) {
    console.error('[identity-slip-pdf] failed to embed photo, continuing without it:', error);
    return false;
  }
}

export function drawPhotoPlaceholder(doc: PdfDoc, x: number, y: number, w: number, h: number) {
  doc.rect(x, y, w, h).fill('#f3f4f6');
  doc.fillColor('#64748b').font('Helvetica').fontSize(8).text('No photograph returned', x, y + h / 2 - 5, { width: w, align: 'center' });
}

/** Text a scanner shows - just our reference, never any identity data. */
export function qrPayload(reference: string): string {
  return `K-TECH-REF:${reference}`;
}

/** Vector QR (crisp at any zoom), drawn module by module. */
export function drawQr(doc: PdfDoc, text: string, x: number, y: number, size: number) {
  const qr = QRCode.create(text, { errorCorrectionLevel: 'M' });
  const modules = qr.modules.size;
  const quiet = 2;
  const cell = size / (modules + quiet * 2);
  doc.rect(x, y, size, size).fill('#ffffff');
  for (let row = 0; row < modules; row += 1) {
    for (let col = 0; col < modules; col += 1) {
      if (qr.modules.get(row, col)) {
        // +0.25 overlap hides hairline seams between neighbouring modules.
        doc.rect(x + (col + quiet) * cell, y + (row + quiet) * cell, cell + 0.25, cell + 0.25);
      }
    }
  }
  doc.fill('#000000');
}

export type SplitFields = {
  nin?: string;
  surname?: string;
  firstName?: string;
  middleName?: string;
  /** First + middle, the way ID layouts print "given names". */
  givenNames?: string;
  dob?: string;
  gender?: string;
  /** Everything else (phone, address, ...), in provider order. */
  rest: IdentitySlipField[];
};

const KNOWN: Record<keyof Omit<SplitFields, 'rest' | 'givenNames'>, string[]> = {
  nin: ['nin', 'national identification number (nin)'],
  surname: ['surname', 'last name'],
  firstName: ['first name'],
  middleName: ['middle name'],
  dob: ['date of birth'],
  gender: ['gender']
};

function present(value: string | null | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed && trimmed !== '****' ? trimmed : undefined;
}

/** Pulls the headline identity fields out by label; the layouts place them, the rest are listed as rows. */
export function splitFields(fields: IdentitySlipField[]): SplitFields {
  const out: SplitFields = { rest: [] };
  for (const field of fields) {
    const label = field.label.trim().toLowerCase();
    const key = (Object.keys(KNOWN) as (keyof typeof KNOWN)[]).find((k) => KNOWN[k].includes(label));
    if (key && out[key] === undefined) {
      out[key] = present(field.value);
    } else if (!key) {
      out.rest.push(field);
    }
  }
  out.givenNames = [out.firstName, out.middleName].filter(Boolean).join(' ') || undefined;
  return out;
}

/** Removes and returns the first remaining field whose label matches. */
export function takeRest(rest: IdentitySlipField[], pattern: RegExp): string | undefined {
  const index = rest.findIndex((field) => pattern.test(field.label) && present(field.value));
  if (index === -1) return undefined;
  const [field] = rest.splice(index, 1);
  return present(field.value);
}
