import PDFDocument from 'pdfkit';

/**
 * Renders a NIN/BVN slip PDF from plain identity fields - for providers
 * (currently FranceVerified) that return JSON data only, no ready-made PDF.
 * Techhub-issued slips already arrive as a finished pdfBase64 and never go
 * through this; this exists so switching a service's provider (see the
 * `provider` column on ServicePricing) never changes what the customer gets
 * to download - same "one PDF per slip purchase" shape either way.
 *
 * Same pdfkit conventions as nin-modification.service.ts's
 * renderModificationPdf() (A4, 50pt margin, Helvetica, base64 via
 * chunks/end) - kept as its own file since both verification.service.ts's
 * slip flow and, if it ever needs one, a future BVN-only flow can reuse it.
 */

export type IdentitySlipPhoto = { base64: string; format?: 'jpeg' | 'png' };

export type IdentitySlipField = { label: string; value: string | null | undefined };

const pageLeft = 50;
const pageRight = 545;

function valueForPdf(value: string | null | undefined): string {
  return value === undefined || value === null || value.trim() === '' || value === '****'
    ? 'N/A'
    : value;
}

/** Accept either raw base64 or a browser-friendly data URL from a provider. */
function imageBuffer(value: string): Buffer {
  const base64 = value
    .trim()
    .replace(/^data:image\/(?:png|jpe?g|webp);base64,/i, '')
    .replace(/\s/g, '');
  return Buffer.from(base64, 'base64');
}

export function renderIdentitySlipPdf(params: {
  title: 'NIN Slip' | 'BVN Slip';
  subtitle: string;
  reference: string;
  fields: IdentitySlipField[];
  photo?: IdentitySlipPhoto;
  issuedAt: Date;
}): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks).toString('base64')));
    doc.on('error', reject);

    doc.rect(pageLeft, 50, pageRight - pageLeft, 72).fill('#102a5c');
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(18).text('MAJOR DATA-LINK', pageLeft + 20, 70);
    doc.font('Helvetica').fontSize(9).text('Identity verification result', pageLeft + 20, 94);
    doc.fillColor('#111111').font('Helvetica-Bold').fontSize(14).text(
      `${params.title} successfully verified`,
      pageLeft,
      145,
      { width: pageRight - pageLeft, align: 'center' }
    );
    doc.font('Helvetica').fontSize(9).fillColor('#555555').text(params.subtitle, pageLeft, 165, {
      width: pageRight - pageLeft,
      align: 'center'
    });

    const photoX = pageLeft;
    const photoY = 210;
    const photoWidth = 170;
    const photoHeight = 205;
    let hasPhoto = false;
    if (params.photo) {
      try {
        doc.rect(photoX, photoY, photoWidth, photoHeight).fill('#f3f4f6');
        doc.image(imageBuffer(params.photo.base64), photoX, photoY, {
          fit: [photoWidth, photoHeight],
          align: 'center',
          valign: 'center'
        });
        hasPhoto = true;
      } catch (error) {
        console.error('[identity-slip-pdf] failed to embed photo, continuing without it:', error);
      }
    }

    const tableX = hasPhoto ? photoX + photoWidth + 24 : pageLeft;
    const tableWidth = pageRight - tableX;
    const labelWidth = Math.min(140, tableWidth * 0.39);
    let y = photoY;
    const rows: IdentitySlipField[] = [
      { label: 'Reference', value: params.reference },
      { label: 'Issued', value: params.issuedAt.toISOString().replace('T', ' ').replace(/\.\d{3}Z$/, ' UTC') },
      ...params.fields
    ];

    for (const field of rows) {
      const value = valueForPdf(field.value);
      const valueHeight = doc.heightOfString(value, { width: tableWidth - labelWidth - 16, lineGap: 2 });
      const rowHeight = Math.max(29, valueHeight + 14);
      if (y + rowHeight > 760) {
        doc.addPage();
        y = 60;
      }
      doc.rect(tableX, y, labelWidth, rowHeight).fill('#eef2f7');
      doc.rect(tableX + labelWidth, y, tableWidth - labelWidth, rowHeight).fill('#ffffff');
      doc.rect(tableX, y, tableWidth, rowHeight).lineWidth(0.5).strokeColor('#94a3b8').stroke();
      doc.fillColor('#111111').font('Helvetica-Bold').fontSize(9).text(field.label, tableX + 9, y + 9, {
        width: labelWidth - 18
      });
      doc.font('Helvetica').text(value, tableX + labelWidth + 8, y + 9, {
        width: tableWidth - labelWidth - 16,
        lineGap: 2
      });
      y += rowHeight;
    }

    const footerY = Math.max(y + 18, hasPhoto ? photoY + photoHeight + 20 : y + 18);
    doc.fillColor('#6b7280').fontSize(8).text(
      'Generated by MAJOR DATA-LINK from verified provider data. This is not a NIMC/NIBSS-issued document.',
      pageLeft,
      footerY,
      { width: pageRight - pageLeft, align: 'center' }
    );

    doc.end();
  });
}
