import PDFDocument from 'pdfkit';

/**
 * Renders a NIN/BVN slip PDF from plain identity fields - for providers
 * (currently FranceVerified) that return JSON data only, no ready-made PDF.
 * Techhub-issued slips already arrive as a finished pdfBase64 and never go
 * through this; this exists so switching a service's provider (see the
 * `provider` column on ServicePricing) never changes what the customer gets
 * to download - same "one PDF per slip purchase" shape either way.
 *
 * Same pdfkit conventions as nin-modification.service.ts's
 * renderModificationPdf() (A4, 50pt margin, Helvetica, base64 via
 * chunks/end) - kept as its own file since both verification.service.ts's
 * slip flow and, if it ever needs one, a future BVN-only flow can reuse it.
 */

export type IdentitySlipPhoto = { base64: string; format?: 'jpeg' | 'png' };

export type IdentitySlipField = { label: string; value: string | null | undefined };

export function renderIdentitySlipPdf(params: {
  title: 'NIN Slip' | 'BVN Slip';
  subtitle: string;
  reference: string;
  fields: IdentitySlipField[];
  photo?: IdentitySlipPhoto;
  issuedAt: Date;
}): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks).toString('base64')));
    doc.on('error', reject);

    doc.fontSize(16).font('Helvetica-Bold').text('MAJOR DATA-LINK', { align: 'center' });
    doc.moveDown(0.2);
    doc.fontSize(13).font('Helvetica-Bold').text(params.title, { align: 'center' });
    doc.fontSize(10).font('Helvetica').fillColor('#555').text(params.subtitle, { align: 'center' });
    doc.moveDown(0.8);
    doc.fillColor('#000');

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ccc').stroke();
    doc.moveDown(0.8);

    // Photo (top-right, when the provider returned one) - text fields start
    // at the same y and wrap around it since pdfkit has no float layout.
    const photoBoxWidth = 120;
    const textWidth = params.photo ? 545 - 50 - photoBoxWidth - 15 : 545 - 50;
    const fieldsTop = doc.y;

    if (params.photo) {
      try {
        const buffer = Buffer.from(params.photo.base64, 'base64');
        doc.image(buffer, 545 - photoBoxWidth, fieldsTop, { width: photoBoxWidth, height: photoBoxWidth * 1.15, fit: [photoBoxWidth, photoBoxWidth * 1.15] });
      } catch (error) {
        // A malformed/truncated base64 photo shouldn't fail the whole slip -
        // the customer still gets every other field.
        console.error('[identity-slip-pdf] failed to embed photo, continuing without it:', error);
      }
    }

    doc.font('Helvetica-Bold').fontSize(10).text('Reference: ', 50, fieldsTop, { continued: true, width: textWidth });
    doc.font('Helvetica').text(params.reference);
    doc.font('Helvetica-Bold').text('Issued: ', 50, doc.y, { continued: true, width: textWidth });
    doc.font('Helvetica').text(params.issuedAt.toISOString());
    doc.moveDown(0.6);

    for (const field of params.fields) {
      const value = field.value === undefined || field.value === null || field.value === '' || field.value === '****' ? '\u2014' : field.value;
      doc.font('Helvetica-Bold').fontSize(10).text(`${field.label}: `, 50, doc.y, { continued: true, width: textWidth });
      doc.font('Helvetica').text(value, { width: textWidth });
    }

    // If the photo box is taller than the text block ended up being, make
    // sure whatever comes next starts below it, not overlapping it.
    if (params.photo) {
      doc.y = Math.max(doc.y, fieldsTop + photoBoxWidth * 1.15 + 10);
    }

    doc.moveDown(1.2);
    doc.fontSize(8).fillColor('#888').text(
      'Generated by MAJOR DATA-LINK from verified provider data. Not a NIMC/NIBSS-issued document.',
      50,
      doc.y,
      { align: 'left' }
    );

    doc.end();
  });
}
