import { useEffect, useRef, useState, type PointerEvent } from 'react';
import { Bot, Send, Sparkles, X } from 'lucide-react';
import { api, ApiError } from '../lib/api';
import { PinConfirmDialog } from './PinConfirmDialog';

type Language = 'choose' | 'ha' | 'en';
type Task = 'choose' | 'data' | 'airtime' | 'fund';
type Message = { text: string; user?: boolean; options?: string[] };
type Plan = { id?: string; plan_id?: string; name?: string; size?: string; price?: number; amount?: number };
type SpeechRecognitionLike = { lang: string; interimResults: boolean; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onerror: (() => void) | null; onend: (() => void) | null; start: () => void; stop: () => void };
type SpeechWindow = Window & { SpeechRecognition?: new () => SpeechRecognitionLike; webkitSpeechRecognition?: new () => SpeechRecognitionLike };
const networks = ['MTN', 'AIRTEL', 'GLO', '9MOBILE'];

export default function MajorAssistant() {
  const [open, setOpen] = useState(false); const [language, setLanguage] = useState<Language>('choose'); const [task, setTask] = useState<Task>('choose'); const [stage, setStage] = useState<'language'|'task'|'network'|'dataType'|'phone'|'plan'|'amount'|'review'|'done'>('language');
  const [messages, setMessages] = useState<Message[]>([{ text: 'Sannu! Welcome to MAJOR AI Assistant.\nChoose a language / Zaɓi yare:', options: ['Hausa', 'English'] }]); const [text, setText] = useState(''); const [network, setNetwork] = useState(''); const [phone, setPhone] = useState(''); const [plans, setPlans] = useState<Plan[]>([]); const [plan, setPlan] = useState<Plan | null>(null); const [amount, setAmount] = useState(0); const [pinOpen, setPinOpen] = useState(false); const [busy, setBusy] = useState(false); const [listening, setListening] = useState(false); const [fabPosition, setFabPosition] = useState({ x: Math.max(16, window.innerWidth - 150), y: Math.max(16, window.innerHeight - 80) }); const inputRef = useRef<HTMLInputElement>(null);
  const [dataType, setDataType] = useState('');
  const ha = language === 'ha'; const tr = (en: string, h: string) => ha ? h : en;
  useEffect(() => { inputRef.current?.focus(); }, [stage, open]);
  useEffect(() => { if (open) { const panels = document.querySelectorAll<HTMLElement>('.overflow-y-auto'); const panel = panels[panels.length - 1]; panel?.scrollTo({ top: panel.scrollHeight, behavior: 'smooth' }); } }, [messages, busy, open]);
  function moveFab(event: PointerEvent<HTMLButtonElement>) { const button = event.currentTarget; button.setPointerCapture(event.pointerId); const move = (e: globalThis.PointerEvent) => setFabPosition({ x: Math.max(8, Math.min(window.innerWidth - 130, e.clientX - 55)), y: Math.max(8, Math.min(window.innerHeight - 55, e.clientY - 25)) }); const stop = () => { button.removeEventListener('pointermove', move); button.removeEventListener('pointerup', stop); }; button.addEventListener('pointermove', move); button.addEventListener('pointerup', stop); }
  const add = (message: Message) => setMessages(prev => [...prev, message]);
  function startVoice() { const Recognition = (window as SpeechWindow).SpeechRecognition ?? (window as SpeechWindow).webkitSpeechRecognition; if (!Recognition) { add({ text: tr('Voice input is not supported in this browser. You can type instead.', 'Wannan browser bai goyi bayan voice input ba. Rubuta saƙonka.') }); return; } const recognition = new Recognition(); recognition.lang = ha ? 'ha-NG' : 'en-NG'; recognition.interimResults = false; recognition.onresult = (event) => { const spoken = event.results[0][0].transcript; setText(spoken); void answer(spoken); }; recognition.onerror = () => setListening(false); recognition.onend = () => setListening(false); setListening(true); recognition.start(); }
  const reset = () => { setTask('choose'); setNetwork(''); setDataType(''); setPhone(''); setPlan(null); setPlans([]); setAmount(0); setStage('task'); add({ text: tr('What else can I help you with?', 'Me kuma zan taimaka maka da shi?'), options: [tr('Buy Data','Siyan Data'), tr('Buy Airtime','Siyan Airtime')] }); };
  async function answer(raw: string) {
    const value = raw.trim(); if (!value || busy) return; setText(''); add({ text: value, user: true }); const lower = value.toLowerCase();
    if (/(human|support|agent|live chat|ma'aikaci|mutum)/.test(lower)) { await handoff('Customer requested human support'); return; }
    const mentionedNetwork = networks.find((item) => lower.includes(item.toLowerCase()));
    if (mentionedNetwork && network && mentionedNetwork !== network && stage !== 'language' && stage !== 'task') { setNetwork(mentionedNetwork); setDataType(''); setPlans([]); setPlan(null); setStage(task === 'data' ? 'dataType' : 'phone'); add({ text: tr(`Okay, I changed the network from ${network} to ${mentionedNetwork}. Let us continue.`, `To, na canza network daga ${network} zuwa ${mentionedNetwork}. Mu ci gaba.`), options: task === 'data' ? ['Corporate','Data Share','Gifting','SME','SME 2','Data Coupon'] : undefined }); return; }
    if (stage === 'language') { const isHa = lower.includes('hausa'); setLanguage(isHa ? 'ha' : 'en'); setStage('task'); add({ text: isHa ? 'Me kake so in taimaka maka da shi?' : 'What would you like to do?', options: isHa ? ['Siyan Data','Siyan Airtime','Cika Wallet'] : ['Buy Data','Buy Airtime','Fund Wallet'] }); return; }
    if (stage === 'task' && /(fund|top ?up|wallet|cika wallet|saka kudi|add money|deposit)/.test(lower)) { setTask('fund'); setStage('amount'); add({ text: tr('How much would you like to add to your wallet?', 'Nawa kake so ka saka a wallet ɗinka?') }); return; }
    if (stage === 'task') {
      type Parsed = { data?: { workflow?: string; fields?: { network?: string; data_type?: string; phone?: string; data_size?: string; amount?: number } } };
      let parsed: Parsed | null = null;
      if (/(last|saved|previous|karshe|ajiye)/.test(lower)) {
        try {
          const saved = await api.get<{ data?: Array<{ phone: string; network?: string; type: string }> }>('/assistant/beneficiaries');
          const wanted = lower.includes('data') ? 'data' : lower.includes('airtime') ? 'airtime' : undefined;
          const recipient = (saved.data ?? []).find((item) => !wanted || item.type === wanted);
          if (!recipient) { add({ text: tr('I could not find a saved recipient yet. Please provide the phone number.', 'Ban samu saved recipient ba tukuna. Don Allah rubuta lambar waya.') }); setStage('phone'); return; }
          parsed = { data: { workflow: recipient.type, fields: { phone: recipient.phone, network: recipient.network } } };
          add({ text: tr(`I found ${recipient.phone}${recipient.network ? ` on ${recipient.network}` : ''} as your recent recipient.`, `Na samu ${recipient.phone}${recipient.network ? ` na ${recipient.network}` : ''} a recent recipients.`) });
        } catch { add({ text: tr('I could not load saved recipients. Please provide the phone number.', 'Ba a iya ɗauko saved recipients ba. Rubuta lambar waya.') }); setStage('phone'); return; }
      } else { try { parsed = await api.post<Parsed>('/assistant/parse', { message: value }); } catch { /* retain the local fallback below */ } }
      void audit({ stage: 'intent', outcome: 'waiting' });
      const fields = parsed?.data?.fields ?? {}; const parsedWorkflow = parsed?.data?.workflow; if (parsedWorkflow && parsedWorkflow !== 'data' && parsedWorkflow !== 'airtime') { add({ text: tr('That service is recognised, but its secure purchase workflow is not active yet. I can connect you to support.', 'Na gane wannan sabis, amma workflow ɗinsa bai fara aiki ba. Zan haɗa ka da support yanzu.'), options: [tr('Talk to support','Yi magana da support')] }); return; } const next: 'data' | 'airtime' = parsedWorkflow === 'data' ? 'data' : parsedWorkflow === 'airtime' ? 'airtime' : lower.includes('data') ? 'data' : 'airtime';
      setTask(next); if (!fields.network) { setStage('network'); add({ text: tr('Which network: MTN, Airtel, Glo or 9mobile?', 'Wanne layi/network: MTN, Airtel, Glo ko 9mobile?'), options: ['MTN','Airtel','Glo','9mobile'] }); return; }
      setNetwork(fields.network); if (next === 'data' && !fields.data_type) { setStage('dataType'); add({ text: tr('Which data type: Corporate, Data Share, Gifting, SME, SME 2 or Data Coupon?', 'Wanne nau’in Data: Corporate, Data Share, Gifting, SME, SME 2 ko Data Coupon?'), options: ['Corporate','Data Share','Gifting','SME','SME 2','Data Coupon'] }); return; }
      setDataType(fields.data_type ?? ''); if (!fields.phone) { setStage('phone'); add({ text: tr('Enter the 11-digit Nigerian phone number.', 'Rubuta lambar Najeriya mai digit 11.') }); return; }
      setPhone(fields.phone); if (next === 'airtime') { if (!fields.amount) { setStage('amount'); add({ text: tr('How much airtime should I buy? (minimum ₦50)', 'Nawa zan saya na airtime? (daga ₦50)') }); return; } setAmount(fields.amount); setStage('review'); await review(null, fields.amount); return; }
      setDataType(fields.data_type ?? '');
      setBusy(true); try { const response = await api.get<{data?: Plan[]}>(`/data/plans/${fields.network}?category=${encodeURIComponent(fields.data_type ?? '')}`); const list = response.data ?? []; setPlans(list); const selected = fields.data_size ? list.find(p => `${p.name ?? ''} ${p.size ?? ''}`.replace(/\s/g,'').toLowerCase().includes(fields.data_size!.toLowerCase())) : undefined; if (selected) { const price = Number(selected.price ?? selected.amount ?? 0); setPlan(selected); setAmount(price); setStage('review'); await review(selected, price); } else { setStage('plan'); add({ text: tr(`Choose a plan (${list.length} available):`, `Zaɓi data plan (${list.length} suna akwai):`), options: list.map(p => `${p.name ?? p.size} — ₦${Number(p.price ?? p.amount ?? 0).toLocaleString()}`) }); } } catch { add({ text: tr('I could not load plans. Please try again.', 'Ba a iya ɗauko plan ba. Sake gwadawa.') }); } finally { setBusy(false); } return;
    }
    if (stage === 'dataType') { const type = lower.includes('corporate') ? 'CORPORATE' : lower.includes('share') ? 'DATA SHARE' : lower.includes('gift') ? 'GIFTING' : lower.includes('sme 2') || lower.includes('sme2') ? 'SME2' : lower.includes('coupon') ? 'DATA COUPON' : lower.includes('sme') ? 'SME' : ''; if (!type) { add({ text: tr('Please choose a data type from the buttons.', 'Zaɓi nau’in Data daga maɓallan.') }); return; } setDataType(type); setStage('phone'); add({ text: tr('Enter the 11-digit Nigerian phone number.', 'Rubuta lambar Najeriya mai digit 11.') }); return; }
    if (stage === 'network') { const n = networks.find(x => lower.includes(x.toLowerCase()) || (x === '9MOBILE' && (lower.includes('nine') || lower.includes('9')))); if (!n) { add({ text: tr('Please choose MTN, Airtel, Glo or 9mobile.', 'Don Allah zaɓi MTN, Airtel, Glo ko 9mobile.') }); return; } setNetwork(n); setStage(task === 'data' ? 'dataType' : 'phone'); add({ text: task === 'data' ? tr('Which data type: Corporate, Data Share, Gifting, SME, SME 2 or Data Coupon?', 'Wanne nau’in Data: Corporate, Data Share, Gifting, SME, SME 2 ko Data Coupon?') : tr('Enter the 11-digit Nigerian phone number.', 'Rubuta lambar Najeriya mai digit 11.'), options: task === 'data' ? ['Corporate','Data Share','Gifting','SME','SME 2','Data Coupon'] : [] }); return; }
    if (stage === 'phone') { const p = value.replace(/\D/g,''); if (p.length !== 11 || !p.startsWith('0')) { add({ text: tr('Please enter a valid 11-digit Nigerian number.', 'Don Allah rubuta lamba mai digit 11.') }); return; } setPhone(p); if (task === 'airtime') { setStage('amount'); add({ text: tr('How much airtime should I buy? (minimum ₦50)', 'Nawa zan saya na airtime? (daga ₦50)') }); return; } setBusy(true); try { const response = await api.get<{data?: Plan[]}>(`/data/plans/${network}?category=${encodeURIComponent(dataType)}`); const list = response.data ?? []; setPlans(list); setStage('plan'); add({ text: tr(`Choose a plan (${list.length} available):`, `Zaɓi data plan (${list.length} suna akwai):`), options: list.map(p => `${p.name ?? p.size} — ₦${Number(p.price ?? p.amount ?? 0).toLocaleString()}`) }); } catch { add({ text: tr('I could not load plans. Please try again.', 'Ba a iya ɗauko plan ba. Sake gwadawa.') }); } finally { setBusy(false); } return; }
    if (stage === 'plan') { const clean = (input: string) => input.toLowerCase().replace(/[^a-z0-9.]/g, ''); const found = plans.find((p) => clean(`${p.name ?? ''} ${p.size ?? ''} ${p.price ?? p.amount ?? ''}`) === clean(value)) ?? plans.find((p) => { const price = Number(p.price ?? p.amount ?? 0); return price > 0 && value.replace(/[^0-9]/g, '') === String(Math.round(price)); }); if (!found) { add({ text: tr('Please use one of the plan buttons.', 'Don Allah zaɓi ɗaya daga maɓallan plan.') }); return; } setPlan(found); setAmount(Number(found.price ?? found.amount ?? 0)); setStage('review'); await review(found, Number(found.price ?? found.amount ?? 0)); return; }
    if (stage === 'amount') { const a = Number(value.replace(/[^0-9.]/g,'')); if (!Number.isFinite(a) || a < 50) { add({ text: tr('Enter ₦50 or more.', 'Rubuta ₦50 ko fiye.') }); return; } if (task === 'fund') { add({ text: tr(`I will take you to secure wallet funding for ₦${a.toLocaleString()}. Your card/bank details and PIN must only be entered on the secure payment page.`, `Zan kai ka secure funding page na ₦${a.toLocaleString()}. Kada ka rubuta card/bank details ko PIN a chat.`), options: [tr('Continue to funding','Ci gaba zuwa funding'), tr('Start again','Fara kuma')] }); setAmount(a); setStage('review'); return; } setAmount(a); setStage('review'); await review(null, a); return; }
    if (stage === 'review') { if (task === 'fund' && /(continue|ci gaba|yes|eh|confirm)/.test(lower)) { window.location.assign(`/fund-wallet?amount=${encodeURIComponent(amount)}`); return; } if (/(yes|eh|confirm)/.test(lower)) setPinOpen(true); else reset(); }
  }
  async function handoff(reason: string) { try { const result = await api.post<{data?: {ticket_id?: string}}>('/assistant/fallback', { reason, stage }); add({ text: tr(`I’ve connected this to human support. Ticket: ${result.data?.ticket_id ?? 'created'}.`, `Na haɗa wannan da human support. Ticket: ${result.data?.ticket_id ?? 'an ƙirƙira'}.`) }); } catch { add({ text: tr('Support handoff is temporarily unavailable. Please open Support from your account menu.', 'Ba a samu support handoff yanzu ba. Buɗe Support daga account menu.') }); } }
  async function review(selectedPlan: Plan | null, price: number) { try { const wallet = await api.get<{balance?: number; data?: {balance?:number}}>('/wallet/balance'); const balance = Number(wallet.balance ?? wallet.data?.balance ?? 0); if (balance < price) { add({ text: tr(`Your wallet balance is ₦${balance.toLocaleString()}, but this needs ₦${price.toLocaleString()}. Fund wallet first.`, `Wallet ɗinka yana da ₦${balance.toLocaleString()}, amma wannan na bukatar ₦${price.toLocaleString()}. Cika wallet farko.`) }); reset(); return; } const item = task === 'data' ? (selectedPlan?.name ?? selectedPlan?.size ?? 'data') : tr('airtime','airtime'); add({ text: tr(`Summary: ${item} on ${network} for ${phone} — ₦${price.toLocaleString()}. Wallet: ₦${balance.toLocaleString()}. Proceed?`, `Takaitawa: ${item} na ${network} zuwa ${phone} — ₦${price.toLocaleString()}. Wallet: ₦${balance.toLocaleString()}. A ci gaba?`), options: [tr('Yes, confirm','Eh, tabbatar'), tr('No, start again','A’a, a fara kuma')] }); } catch { add({ text: tr('I could not check your wallet. I can connect you to support.', 'Ba a iya duba wallet ba. Zan haɗa ka da support.'), options: [tr('Talk to support','Yi magana da support')] }); } }
  async function audit(event: { stage: string; outcome: 'started'|'waiting'|'success'|'failed'|'fallback'|'cancelled'; error_code?: string; transaction_ref?: string }) { try { await api.post('/assistant/events', { intent: task, ...event }); } catch { /* observability must never block a customer */ } }
  async function purchase() { setPinOpen(false); setBusy(true); try { const res = task === 'data' ? await api.post<{status:boolean;message?:string;data?:{reference?:string}}>('/data/purchase',{network,plan_id:plan?.id ?? plan?.plan_id,phone,amount}) : await api.post<{status:boolean;message?:string;data?:{reference?:string}}>('/airtime/purchase',{network,phone,amount}); void audit({ stage: 'purchase', outcome: res.status ? 'success' : 'failed', transaction_ref: res.data?.reference }); add({ text: res.status ? tr(res.message ?? 'Purchase complete.', res.message ?? 'An gama siya.') : tr(res.message ?? 'Purchase failed.', res.message ?? 'Siyan ta gaza.') }); } catch (error) { void audit({ stage: 'purchase', outcome: 'failed', error_code: error instanceof ApiError ? error.code : 'PURCHASE_ERROR' }); add({ text: error instanceof ApiError ? error.message : tr('Purchase failed. Please try again.','Siyan ta gaza. Sake gwadawa.') }); } finally { setBusy(false); reset(); } }
  return <><button aria-label="Open MAJOR AI Assistant" onPointerDown={moveFab} onClick={()=>setOpen(true)} style={{ left: fabPosition.x, top: fabPosition.y, touchAction: 'none' }} className="fixed z-[60] flex items-center gap-2 rounded-full bg-brand-600 px-4 py-3 text-sm font-bold text-white shadow-2xl shadow-brand-900/40 transition hover:scale-105"><Sparkles size={18} className="animate-pulse"/> AI Help</button>{open && <section className="fixed bottom-4 right-4 z-50 flex h-[min(680px,calc(100vh-32px))] w-[min(410px,calc(100vw-32px))] flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-center justify-between bg-brand-700 px-4 py-4 text-white"><div className="flex items-center gap-2"><Bot/><div><b>MAJOR AI Assistant</b><p className="text-xs text-white/75">Secure service guide</p></div></div><button onClick={()=>setOpen(false)} aria-label="Close assistant"><X/></button></header><div className="bg-brand-50 px-4 py-2 text-center text-[11px] text-brand-800">No external AI • PIN is never typed in chat</div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((m,i)=><div key={i} className={m.user?'ml-10 text-right':'mr-6'}><div className={`inline-block whitespace-pre-line rounded-2xl px-3 py-2 text-sm ${m.user?'bg-brand-600 text-white':'bg-slate-100 text-slate-800'}`}>{m.text}</div>{m.options && <div className="mt-2 flex flex-wrap gap-2">{m.options.map(o=><button key={o} onClick={()=>answer(o)} className="rounded-full border border-brand-200 bg-white px-3 py-1.5 text-xs font-semibold text-brand-700 hover:bg-brand-50">{o}</button>)}</div>}</div>)}</div>{busy && <div className="h-1 animate-pulse bg-brand-500"/>}<form onSubmit={e=>{e.preventDefault();answer(text)}} className="flex gap-2 border-t p-3"><button type="button" aria-label="Speak" onClick={startVoice} className={`rounded-xl p-2 ${listening?'bg-rose-100 text-rose-700':'bg-brand-50 text-brand-700'}`}>{listening ? '●' : '🎙️'}</button><input ref={inputRef} autoComplete="tel" inputMode={stage === 'phone' ? 'tel' : stage === 'amount' ? 'decimal' : 'text'} value={text} onChange={e=>setText(e.target.value)} placeholder={stage === 'phone' ? tr('Enter phone number…','Rubuta lambar waya…') : tr('Type your reply…','Rubuta amsarka…')} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-brand-500"/><button disabled={busy} className="rounded-xl bg-brand-600 p-2 text-white disabled:opacity-50"><Send size={18}/></button></form></section>}<PinConfirmDialog open={pinOpen} onClose={()=>setPinOpen(false)} onVerified={purchase}/></>;
}
